objects/Expense__c.object
<CustomObject>
    <description>Exnpense object</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Enter your amount</description>
        <inlineHelpText>put amount</inlineHelpText>
        <label>Amount</label>
        <precision>16</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Enter Event Date</description>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Enter event name</description>
        <label>Event</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense_name</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <label>Contribution Amount</label>
        <precision>15</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Member</relationshipLabel>
        <relationshipName>Expense_Member1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <description>Member are their</description>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Member</relationshipLabel>
        <relationshipName>Expense_Member</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Member</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Expense mem id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Member</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <description>Member Object</description>
    <fields>
        <fullName>Cus_email__c</fullName>
        <label>Cus_email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile_NO__c</fullName>
        <description>Enter mobile no</description>
        <label>Mobile NO</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter your name</description>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member_name</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseTest.cls
@isTest

public class ExpenseTest {

 public testMethod static void myTest(){
      
        Expense__c expense = new Expense__c();
        
        //expense object's field
         
        expense.Amount__c=1000.80;
        expense.Event__c='party';
        expense.Date__c=date.today();
       
        insert expense; //insert object
       
        Member__c member = new Member__c();
        
        //member object's field
        
        member.Name__c='xyz';
        member.Cus_email__c='abc@abc.com';
        member.Mobile_NO__c='+91-9093397692';
        
        insert member; //insert memnber
       
        Expense_Member__c expmem = new Expense_Member__c();
       
       //Juncton object's field
       
        expmem.Member__c=member.Id;
        expmem.Expense__c=expense.Id;
        expmem.Contribution_Amount__c=100.50;
       
        insert expmem; //insert Junction obj
       
        ExpenseEXT expExt = new ExpenseEXT(new ApexPages.StandardController(expense));
        
        List<Expense_Member__c> ge = new List<Expense_Member__c>();
       
        ge = expExt.getExpMembers();
       
       
}
}