objects/Expense__c.object
<CustomObject>
    <description>Exnpense object</description>
    <label>Expense</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense_name</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <label>Contribution Amount</label>
        <precision>15</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Member</relationshipLabel>
        <relationshipName>Expense_Member1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <description>Member are their</description>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Member</relationshipLabel>
        <relationshipName>Expense_Member</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Member</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Expense mem id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Member</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <description>Member Object</description>
    <fields>
        <fullName>Name__c</fullName>
        <description>Enter your name</description>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member_name</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseEXT.cls
public with sharing class ExpenseEXT {

    public Expense__c expObj{get;set;}
    public List<Expense_Member__c> memExp{get;set;}
    
    public ExpenseEXT(ApexPages.StandardController controller) {
    
        expObj = (Expense__c)controller.getRecord();
        memExp=getExpMembers();
    }
    
    public List<Expense_Member__c> getExpMembers(){
    
        return [Select Member__r.Name__c,Contribution_Amount__c from Expense_Member__c where Expense__c =: expObj.Id];
    }
}